apiVersion: batch/v1
kind: Job
metadata:
  name: l1metml-root-16-6-alpha10
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nautilus.optiputer.net/jmduarte/l1metml:latest
        command:
        - "/bin/bash"
        - "-c"
        - "git clone https://github.com/hanhiller/L1METML &&
           cd L1METML &&
           python train.py --dataType root --input /l1metmlvol/TTbar_PU200_110X_1M/ --output /l1metmlvol/root-16-6-alpha10/ --mode 1 --epochs 100 --quantized"
        volumeMounts:
        - mountPath: /l1metmlvol
          name: l1metmlvol
        resources:
          limits:
            memory: 100Gi
            cpu: "10"
          requests:
            memory: 50Gi
            cpu: "10"
      volumes:
      - name: l1metmlvol
        persistentVolumeClaim:
          claimName: l1metmlvol

      restartPolicy: Never
  backoffLimit: 0
