apiVersion: batch/v1
kind: Job
metadata:
  name: l1metml-root-main-merge-hyper-16-32
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nautilus.optiputer.net/jmduarte/l1metml:latest
        command:
        - "/bin/bash"
        - "-c"
        - " git clone https://github.com/hanhiller/L1METML &&
            cd L1METML &&
            python train.py --workflowType root --input /l1metmlvol/TTbar_PU200_110X_1M/ --output /l1metmlvol/root-main-merge-quan-16-32/ --mode 1 --epochs 100"
        volumeMounts:
        - mountPath: /l1metmlvol
          name: l1metmlvol
        resources:
          limits:
            memory: 50Gi
            cpu: "10"
          requests:
            memory: 25Gi
            cpu: "10"
      volumes:
      - name: l1metmlvol
        persistentVolumeClaim:
          claimName: l1metmlvol

      restartPolicy: Never
  backoffLimit: 0
