apiVersion: batch/v1
kind: Job
metadata:
  name: l1metml-training-h5-2048-2epochs
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nautilus.optiputer.net/jmduarte/l1metml:latest
        command:
        - "/bin/bash"
        - "-c"
        - " git clone https://github.com/hanhiller/L1METML &&
            cd L1METML &&
            python -m cProfile -o /l1metmlvol/l1metml-training-h5-2048-2epochs.dat train.py --dataType h5 --input /l1metmlvol/TTbar_PU200_110X_1M/ --output /l1metmlvol/h5_training_2048-2epochs_customLoss/ --mode 1 --epochs 2 &&
            pip install snakeviz &&
            snakeviz -s safari /l1metmlvol/l1metml-training-h5-2048-2epochs.dat"
        volumeMounts:
        - mountPath: /l1metmlvol
          name: l1metmlvol
        resources:
          limits:
            memory: 50Gi
            cpu: "6"
          requests:
            memory: 25Gi
            cpu: "6"
      volumes:
      - name: l1metmlvol
        persistentVolumeClaim:
          claimName: l1metmlvol

      restartPolicy: Never
  backoffLimit: 0
